# Generated by Django 2.1.1 on 2020-03-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newspost_avilable'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='urlyoutube',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
