# Generated by Django 2.1.1 on 2020-03-28 21:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200302_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='textcut',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True),
        ),
    ]
