# Generated by Django 2.1.1 on 2020-03-29 07:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200329_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='textcut',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
