# Generated by Django 3.0.4 on 2020-03-29 16:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200329_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
