# Generated by Django 3.0.7 on 2020-06-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200402_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='visite_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
