# Generated by Django 3.2.7 on 2021-09-12 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20210903_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('author', models.CharField(choices=[('admin', 'Администратор'), ('student', 'Ученик')], max_length=100, verbose_name='Кто отправил')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Собщение',
                'verbose_name_plural': 'Собщения',
            },
        ),
        migrations.RemoveField(
            model_name='messageuser',
            name='author',
        ),
        migrations.DeleteModel(
            name='MessageAdmin',
        ),
        migrations.DeleteModel(
            name='MessageUser',
        ),
    ]
