# Generated by Django 3.2.7 on 2021-09-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210912_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('outgoing', 'Исходящие'), ('incoming', 'Входящие')], default='', max_length=100, verbose_name='Тип сообщения'),
            preserve_default=False,
        ),
    ]
