# Generated by Django 3.2.7 on 2021-09-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210903_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='avilable',
            new_name='is_available',
        ),
    ]
