# Generated by Django 4.0 on 2022-01-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_imagesforarticle_article'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='file',
            table='file',
        ),
        migrations.AlterModelTable(
            name='imagesforarticle',
            table='image',
        ),
        migrations.AlterModelTable(
            name='like',
            table='like',
        ),
    ]
