# Generated by Django 4.0 on 2022-01-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_table_alter_category_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.file')),
            ],
            options={
                'verbose_name': 'Тэг для файла',
                'verbose_name_plural': 'Тэги для файлов',
            },
        ),
    ]
