# Generated by Django 4.0 on 2022-01-14 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_tagfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.file'),
        ),
        migrations.AlterModelTable(
            name='tagfile',
            table='tag_file',
        ),
    ]
