# Generated by Django 3.0.6 on 2020-05-17 20:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('classNumber', models.CharField(choices=[('5', '5 класс'), ('6', '6 класс'), ('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], max_length=255, verbose_name='Класс')),
            ],
        ),
        migrations.CreateModel(
            name='TaskHomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('task', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Задание')),
                ('datePub', models.DateTimeField(verbose_name='Дата сдачи')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTaskHomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.CharField(choices=[('2', 'Неудовлетворительно'), ('3', 'Удовлетворительно'), ('4', 'Хорошо'), ('5', 'Отлично')], max_length=255, verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Коментарий')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworkForStudents.PersonModel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworkForStudents.TaskHomeWork')),
            ],
        ),
    ]
