# Generated by Django 3.2.7 on 2021-09-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210903_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='commets_answer',
            new_name='comments_answer',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='avilable',
            new_name='available',
        ),
    ]
