# Generated by Django 3.2.7 on 2021-09-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210912_1051'),
        ('task', '0003_auto_20210911_1543'),
    ]

    operations = [
    ]
