# Generated by Django 4.0 on 2022-01-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_possiblequestionanswer_testquestion_testsession_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possiblequestionanswer',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='testsession',
            options={'verbose_name': 'Тест ученика', 'verbose_name_plural': 'Тесты учеников'},
        ),
        migrations.AlterModelOptions(
            name='useranswerforquestion',
            options={'verbose_name': 'Ответ на вопрос', 'verbose_name_plural': 'Ответы на вопросы'},
        ),
        migrations.AddField(
            model_name='testtask',
            name='class_student',
            field=models.CharField(choices=[('5', '5 класс'), ('6', '6 класс'), ('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], default='', max_length=15, verbose_name='Класс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение для вопроса'),
        ),
    ]
