# Generated by Django 4.0 on 2022-01-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_possiblequestionanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtask',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
