# Generated by Django 4.0 on 2022-01-10 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_testtask_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='end_time',
            field=models.DateTimeField(blank=True, verbose_name='Время завершения'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала'),
        ),
    ]
