# Generated by Django 4.0 on 2022-01-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_testsession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения'),
        ),
    ]
