# Generated by Django 4.0 on 2022-01-13 07:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('task', '0012_alter_testsession_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ на задание', 'verbose_name_plural': 'Ответы на задания'},
        ),
        migrations.AddField(
            model_name='answer',
            name='craeted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время завершения'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='user.user'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='duration_session',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=300), '5 минут'), (datetime.timedelta(seconds=600), '10 минут'), (datetime.timedelta(seconds=1200), '20 минут'), (datetime.timedelta(seconds=1800), '30 минут'), (datetime.timedelta(seconds=2700), '45 минут'), (datetime.timedelta(seconds=3600), '60 минут'), (datetime.timedelta(seconds=5400), '1 ч 30 минут'), (datetime.timedelta(seconds=7200), '2 ч')], verbose_name='Время на прохождение'),
        ),
    ]
