# Generated by Django 4.0 on 2022-01-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_alter_answer_options_answer_craeted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
